#GNU_INSTALL_ROOT ?= /usr/local/gcc-arm-none-eabi-6-2017-q2-update/bin/
GNU_INSTALL_ROOT ?= /mnt/c/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/bin/
GNU_VERSION ?= 6.3.1
GNU_PREFIX ?= arm-none-eabi
